package Acme::CPANLists::Import::PerlAdvent::2007;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2007/] (retrieved on 2016-11-07). Visit the URL for the full contents.",entries=>[{module=>"Data::ICal"},{module=>"Parallel::Jobs"},{module=>"DBIx::Profile"},{module=>"Test::Differences"},{module=>"File::Which"},{module=>"File::ReadBackwards"},{module=>"Math::Combinatorics"},{module=>"Sub::Versive"},{module=>"forks"},{module=>"Pod::Advent"},{module=>"Pod::Simple"},{module=>"Acme::Curses::Marquee"},{module=>"B::Fathom"},{module=>"DBD::AnyData"},{module=>"DBD::CSV"},{module=>"Text::CSV"},{module=>"Text::vCard"},{module=>"Time::Out"}],summary=>"Modules mentioned in Perl Advent Calendar 2007"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2007

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2007/> (retrieved on 2016-11-07). Visit the URL for the full contents.

