#!/usr/bin/env perl

use 5.010;
use strict;
use warnings;
use FindBin '$Bin';

use App::CreateAcmeCPANListsImportModules;
use Perinci::Sub::Util qw(gen_curried_sub);
use Perinci::CmdLine::Any;

gen_curried_sub(
    'App::CreateAcmeCPANListsImportModules::create_acme_cpanlists_import_modules',
    {
        modules => [
            {
                name => '2007',
                url => "http://perladvent.org/2007/",
                extract_urls => [map {"http://perladvent.org/2007/$_/"}
                                     1..9, 11, 16..19, 23..25],
                summary => 'Modules mentioned in Perl Advent Calendar 2007',
            },
            {
                name => '2007_12_01',
                summary => "Modules mentioned in Perl Advent Calendar 2007 (day 1)",
                url => "http://perladvent.org/2007/1/",
            },
            {
                name => '2007_12_02',
                summary => "Modules mentioned in Perl Advent Calendar 2007 (day 2)",
                url => "http://perladvent.org/2007/2/",
            },
            {
                name => '2007_12_03',
                summary => "Modules mentioned in Perl Advent Calendar 2007 (day 3)",
                url => "http://perladvent.org/2007/3/",
            },
            {
                name => '2007_12_04',
                summary => "Modules mentioned in Perl Advent Calendar 2007 (day 4)",
                url => "http://perladvent.org/2007/4/",
            },
            {
                name => '2007_12_05',
                summary => "Modules mentioned in Perl Advent Calendar 2007 (day 5)",
                url => "http://perladvent.org/2007/5/",
            },
            {
                name => '2007_12_06',
                summary => "Modules mentioned in Perl Advent Calendar 2007 (day 6)",
                url => "http://perladvent.org/2007/6/",
                add_modules => ['App::XLSperl'],
            },
            {
                name => '2007_12_07',
                summary => "Modules mentioned in Perl Advent Calendar 2007 (day 7)",
                url => "http://perladvent.org/2007/7/",
                add_modules => ['Date::Format', 'Date::Parse', 'Date::Language'],
            },
            {
                name => '2007_12_08',
                summary => "Modules mentioned in Perl Advent Calendar 2007 (day 8)",
                url => "http://perladvent.org/2007/8/",
            },
            {
                name => '2007_12_09',
                summary => "Modules mentioned in Perl Advent Calendar 2007 (day 9)",
                url => "http://perladvent.org/2007/9/",
            },
            {
                name => '2007_12_11',
                summary => "Modules mentioned in Perl Advent Calendar 2007 (day 11)",
                url => "http://perladvent.org/2007/11/",
            },
            {
                name => '2007_12_16',
                summary => "Modules mentioned in Perl Advent Calendar 2007 (day 16)",
                url => "http://perladvent.org/2007/16/",
                # unspecific url
                add_modules => ['DateTime::TimeZone'],
            },
            {
                name => '2007_12_17',
                summary => "Modules mentioned in Perl Advent Calendar 2007 (day 17)",
                url => "http://perladvent.org/2007/17/",
            },
            {
                name => '2007_12_18',
                summary => "Modules mentioned in Perl Advent Calendar 2007 (day 18)",
                url => "http://perladvent.org/2007/18/",
            },
            # no mention of modules
            #{
            #    name => '2007_12_19',
            #    summary => "Modules mentioned in Perl Advent Calendar 2007 (day 19)",
            #    url => "http://perladvent.org/2007/19/",
            #},
            {
                name => '2007_12_23',
                summary => "Modules mentioned in Perl Advent Calendar 2007 (day 23)",
                url => "http://perladvent.org/2007/23/",
            },
            {
                name => '2007_12_24',
                summary => "Modules mentioned in Perl Advent Calendar 2007 (day 24)",
                url => "http://perladvent.org/2007/24/",
            },
            {
                name => '2007_12_25',
                summary => "Modules mentioned in Perl Advent Calendar 2007 (day 25)",
                url => "http://perladvent.org/2007/25/",
            },
        ],
        namespace => 'Acme::CPANLists::Import::PerlAdvent',
        user_agent => 'Mozilla/5.0',
        dist_dir => "$Bin/..",
    },
    'app',
);

Perinci::CmdLine::Any->new(
    url => '/main/app',
    log => 1,
)->run;
